// Automatically generated wrapper file 
// Generated by scripts/build_jswrapper.py

#include "jswrapper.h"
#include "jsnative.h"
#include "../../Espruino/src/jswrap_array.h"
#include "../../Espruino/src/jswrap_arraybuffer.h"
#include "../../Espruino/src/jswrap_dataview.h"
#include "../../Espruino/src/jswrap_date.h"
#include "../../Espruino/src/jswrap_error.h"
#include "../../Espruino/src/jswrap_functions.h"
#include "../../Espruino/src/jswrap_json.h"
#include "jswrap_math.h"
#include "../../Espruino/src/jswrap_modules.h"
#include "../../Espruino/src/jswrap_number.h"
#include "../../Espruino/src/jswrap_object.h"
#include "../../Espruino/src/jswrap_process.h"
#include "../../Espruino/src/jswrap_promise.h"
#include "../../Espruino/src/jswrap_regexp.h"
#include "../../Espruino/src/jswrap_string.h"
#include "jswrap_board.h"
#include "../devices/jswrap_motor.h"
#include "../devices/jswrap_led.h"
#include "../devices/jswrap_range.h"


// -----------------------------------------------------------------------------------------
// ----------------------------------------------------------------- AUTO-GENERATED WRAPPERS
// -----------------------------------------------------------------------------------------

static JsVar* gen_jswrap_Array_pop(JsVar *parent) {
  return jsvArrayPop(parent);
}

static bool gen_jswrap_Array_isArray(JsVar* var) {
  return jsvIsArray(var);
}

static JsVar* gen_jswrap_Uint8Array_Uint8Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT8, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint8ClampedArray_Uint8ClampedArray(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT8|ARRAYBUFFERVIEW_CLAMPED, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int8Array_Int8Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT8, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint16Array_Uint16Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT16, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int16Array_Int16Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT16, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint32Array_Uint32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int32Array_Int32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Float32Array_Float32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_FLOAT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Float64Array_Float64Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_FLOAT64, arr, byteOffset, length);
}

static JsVar* gen_jswrap_ArrayBufferView_buffer(JsVar *parent) {
  return jsvLock(jsvGetFirstChild(parent));
}

static JsVarInt gen_jswrap_ArrayBufferView_byteLength(JsVar *parent) {
  return (JsVarInt)(parent->varData.arraybuffer.length * JSV_ARRAYBUFFER_GET_SIZE(parent->varData.arraybuffer.type));
}

static JsVarInt gen_jswrap_ArrayBufferView_byteOffset(JsVar *parent) {
  return parent->varData.arraybuffer.byteOffset;
}

static JsVar* gen_jswrap_DataView_getFloat32(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_FLOAT32, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getFloat64(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_FLOAT64, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getInt8(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_INT8, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getInt16(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_INT16, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getInt32(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_INT32, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getUint8(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_UINT8, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getUint16(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_UINT16, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getUint32(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_UINT32, byteOffset, littleEndian);
}

static void gen_jswrap_DataView_setFloat32(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_FLOAT32, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setFloat64(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_FLOAT64, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setInt8(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_INT8, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setInt16(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_INT16, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setInt32(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_INT32, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setUint8(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_UINT8, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setUint16(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_UINT16, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setUint32(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_UINT32, byteOffset, value, littleEndian);
}

static JsVarFloat gen_jswrap_Math_E() {
  return 2.718281828459045;
}

static JsVarFloat gen_jswrap_Math_PI() {
  return PI;
}

static JsVarFloat gen_jswrap_Math_LN2() {
  return 0.6931471805599453;
}

static JsVarFloat gen_jswrap_Math_LN10() {
  return 2.302585092994046;
}

static JsVarFloat gen_jswrap_Math_LOG2E() {
  return 1.4426950408889634;
}

static JsVarFloat gen_jswrap_Math_LOG10E() {
  return 0.4342944819032518;
}

static JsVarFloat gen_jswrap_Math_SQRT2() {
  return 1.4142135623730951;
}

static JsVarFloat gen_jswrap_Math_SQRT1_2() {
  return 0.7071067811865476;
}

static JsVarFloat gen_jswrap_Math_acos(JsVarFloat x) {
  return jswrap_math_atan(jswrap_math_sqrt(1-x*x) / x);
}

static JsVarFloat gen_jswrap_Math_asin(JsVarFloat x) {
  return jswrap_math_atan(x / jswrap_math_sqrt(1-x*x));
}

static JsVarFloat gen_jswrap_Math_cos(JsVarFloat theta) {
  return jswrap_math_sin(theta + (PI/2));
}

static JsVarFloat gen_jswrap_Math_random() {
  return (JsVarFloat)rand() / (JsVarFloat)RAND_MAX;
}

static JsVarFloat gen_jswrap_Math_tan(JsVarFloat theta) {
  return jswrap_math_sin(theta) / jswrap_math_sin(theta+(PI/2));
}

static JsVarFloat gen_jswrap_Math_min(JsVar* args) {
  return jswrap_math_minmax(args, false);
}

static JsVarFloat gen_jswrap_Math_max(JsVar* args) {
  return jswrap_math_minmax(args, true);
}

static JsVarFloat gen_jswrap_NaN() {
  return NAN;
}

static JsVarFloat gen_jswrap_Infinity() {
  return INFINITY;
}

static JsVarFloat gen_jswrap_Number_NaN() {
  return NAN;
}

static JsVarFloat gen_jswrap_Number_MAX_VALUE() {
  return DBL_MAX;
}

static JsVarFloat gen_jswrap_Number_MIN_VALUE() {
  return DBL_MIN;
}

static JsVarFloat gen_jswrap_Number_NEGATIVE_INFINITY() {
  return -INFINITY;
}

static JsVarFloat gen_jswrap_Number_POSITIVE_INFINITY() {
  return INFINITY;
}

static int gen_jswrap_HIGH() {
  return 1;
}

static int gen_jswrap_LOW() {
  return 0;
}

static JsVar* gen_jswrap_Object_keys(JsVar* object) {
  return jswrap_object_keys_or_property_names(object, false, false);
}

static JsVar* gen_jswrap_Object_getOwnPropertyNames(JsVar* object) {
  return jswrap_object_keys_or_property_names(object, true, false);
}

static JsVar* gen_jswrap_process_version() {
  return jsvNewFromString(JS_VERSION);
}

static int gen_jswrap_String_indexOf(JsVar *parent, JsVar* substring, JsVar* fromIndex) {
  return jswrap_string_indexOf(parent, substring, fromIndex, false);
}

static int gen_jswrap_String_lastIndexOf(JsVar *parent, JsVar* substring, JsVar* fromIndex) {
  return jswrap_string_indexOf(parent, substring, fromIndex, true);
}

static JsVar* gen_jswrap_String_toLowerCase(JsVar *parent) {
  return jswrap_string_toUpperLowerCase(parent, false);
}

static JsVar* gen_jswrap_String_toUpperCase(JsVar *parent) {
  return jswrap_string_toUpperLowerCase(parent, true);
}

static JsVarFloat gen_jswrap_getTime() {
  return (JsVarFloat)jshGetSystemTime() / (JsVarFloat)jshGetTimeFromMilliseconds(1000);
}

static JsVar* gen_jswrap_ArrayBufferView_ArrayBufferView() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_JSON_JSON() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Math_Math() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Modules_Modules() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_process_process() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_LED_LED() {
  return jsvNewWithFlags(JSV_OBJECT);
}

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------


// Binary search coded to allow for JswSyms to be in flash on the esp8266 where they require
// word accesses
JsVar *jswBinarySearch(const JswSymList *symbolsPtr, JsVar *parent, const char *name) {
  uint8_t symbolCount = READ_FLASH_UINT8(&symbolsPtr->symbolCount);
  int searchMin = 0;
  int searchMax = symbolCount - 1;
  while (searchMin <= searchMax) {
    int idx = (searchMin+searchMax) >> 1;
    const JswSymPtr *sym = &symbolsPtr->symbols[idx];
    unsigned short strOffset = READ_FLASH_UINT16(&sym->strOffset);
    int cmp = FLASH_STRCMP(name, &symbolsPtr->symbolChars[strOffset]);
    if (cmp==0) {
      unsigned short functionSpec = READ_FLASH_UINT16(&sym->functionSpec);
      if ((functionSpec & JSWAT_EXECUTE_IMMEDIATELY_MASK) == JSWAT_EXECUTE_IMMEDIATELY)
        return jsnCallFunction(sym->functionPtr, functionSpec, parent, 0, 0);
      return jsvNewNativeFunction(sym->functionPtr, functionSpec);
    } else {
      if (cmp<0) {
        // searchMin is the same
        searchMax = idx-1;
      } else {
        searchMin = idx+1;
        // searchMax is the same
      }
    }
  }
  return 0;
}


// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------


#ifdef ESP8266
#define FLASH_SECT __attribute__((section(".irom.literal2"))) __attribute__((aligned(4)))
#else
#define FLASH_SECT
#endif

static const JswSymPtr jswSymbols_global[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_constructor},
  {6, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_arraybuffer_constructor},
  {18, JSWAT_JSVAR, (void (*)(void))gen_jswrap_ArrayBufferView_ArrayBufferView},
  {34, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_boolean_constructor},
  {42, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))jswrap_dataview_constructor},
  {51, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_constructor},
  {56, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_error_constructor},
  {62, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Float32Array_Float32Array},
  {75, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Float64Array_Float64Array},
  {88, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_function_constructor},
  {97, JSWAT_INT32 | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_HIGH},
  {102, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Infinity},
  {111, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Int16Array_Int16Array},
  {122, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Int32Array_Int32Array},
  {133, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Int8Array_Int8Array},
  {143, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_internalerror_constructor},
  {157, JSWAT_JSVAR, (void (*)(void))gen_jswrap_JSON_JSON},
  {162, JSWAT_JSVAR, (void (*)(void))gen_jswrap_LED_LED},
  {166, JSWAT_INT32 | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_LOW},
  {170, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Math_Math},
  {175, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Modules_Modules},
  {183, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_motor_constructor},
  {189, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_NaN},
  {193, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_number_constructor},
  {200, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_constructor},
  {207, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_constructor},
  {215, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_range_constructor},
  {221, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_referenceerror_constructor},
  {236, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_regexp_constructor},
  {243, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_constructor},
  {250, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_syntaxerror_constructor},
  {262, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_typeerror_constructor},
  {272, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint16Array_Uint16Array},
  {284, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint32Array_Uint32Array},
  {296, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint8Array_Uint8Array},
  {307, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint8ClampedArray_Uint8ClampedArray},
  {325, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_arguments},
  {335, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_atob},
  {340, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_btoa},
  {345, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))jswrap_interface_changeInterval},
  {360, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_interface_clearInterval},
  {374, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_interface_clearTimeout},
  {387, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_decodeURIComponent},
  {406, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_encodeURIComponent},
  {425, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_eval},
  {430, JSWAT_JSVARFLOAT, (void (*)(void))gen_jswrap_getTime},
  {438, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_isNaN},
  {444, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_parseFloat},
  {455, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_parseInt},
  {464, JSWAT_JSVAR, (void (*)(void))gen_jswrap_process_process},
  {472, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_require},
  {480, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*3)), (void (*)(void))jswrap_interface_setInterval},
  {492, JSWAT_VOID | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_interactive_setTime},
  {500, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*3)), (void (*)(void))jswrap_interface_setTimeout}
};
static const unsigned char jswSymbolIndex_global = 0;
static const JswSymPtr jswSymbols_Array_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_concat},
  {7, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_every},
  {13, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_array_fill},
  {18, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_filter},
  {25, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_forEach},
  {33, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_indexOf},
  {41, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_join},
  {46, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_object_length},
  {53, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_map},
  {57, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))gen_jswrap_Array_pop},
  {61, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_push},
  {66, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_reduce},
  {73, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_array_reverse},
  {81, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_array_shift},
  {87, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_slice},
  {93, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_some},
  {98, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_sort},
  {103, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*3)), (void (*)(void))jswrap_array_splice},
  {110, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_toString},
  {119, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_unshift}
};
static const unsigned char jswSymbolIndex_Array_proto = 1;
static const JswSymPtr jswSymbols_Array[] FLASH_SECT = {
  {0, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Array_isArray}
};
static const unsigned char jswSymbolIndex_Array = 2;
static const JswSymPtr jswSymbols_ArrayBufferView_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_ArrayBufferView_buffer},
  {7, JSWAT_INT32 | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_ArrayBufferView_byteLength},
  {18, JSWAT_INT32 | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_ArrayBufferView_byteOffset},
  {29, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_array_fill},
  {34, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_forEach},
  {42, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_indexOf},
  {50, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_join},
  {55, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_arraybufferview_map},
  {59, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_reduce},
  {66, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_array_reverse},
  {74, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))jswrap_arraybufferview_set},
  {78, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_slice},
  {84, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_sort}
};
static const unsigned char jswSymbolIndex_ArrayBufferView_proto = 3;
static const JswSymPtr jswSymbols_DataView_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getFloat32},
  {11, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getFloat64},
  {22, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getInt16},
  {31, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getInt32},
  {40, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getInt8},
  {48, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getUint16},
  {58, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getUint32},
  {68, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getUint8},
  {77, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setFloat32},
  {88, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setFloat64},
  {99, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setInt16},
  {108, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setInt32},
  {117, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setInt8},
  {125, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setUint16},
  {135, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setUint32},
  {145, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setUint8}
};
static const unsigned char jswSymbolIndex_DataView_proto = 4;
static const JswSymPtr jswSymbols_Date[] FLASH_SECT = {
  {0, JSWAT_JSVARFLOAT, (void (*)(void))jswrap_date_now},
  {4, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_parse}
};
static const unsigned char jswSymbolIndex_Date = 5;
static const JswSymPtr jswSymbols_Date_proto[] FLASH_SECT = {
  {0, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getDate},
  {8, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getDay},
  {15, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getFullYear},
  {27, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getHours},
  {36, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getMilliseconds},
  {52, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getMinutes},
  {63, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getMonth},
  {72, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getSeconds},
  {83, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getTime},
  {91, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_setTime},
  {99, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getTimezoneOffset},
  {117, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_setDate},
  {125, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_date_setFullYear},
  {137, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)) | (JSWAT_JSVAR << (JSWAT_BITS*4)), (void (*)(void))jswrap_date_setHours},
  {146, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_setMilliseconds},
  {162, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_date_setMinutes},
  {173, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_date_setMonth},
  {182, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_date_setSeconds},
  {193, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_toISOString},
  {205, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_toString},
  {214, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_toUTCString},
  {226, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getTime}
};
static const unsigned char jswSymbolIndex_Date_proto = 6;
static const JswSymPtr jswSymbols_Error_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_Error_proto = 7;
static const JswSymPtr jswSymbols_SyntaxError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_SyntaxError_proto = 8;
static const JswSymPtr jswSymbols_TypeError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_TypeError_proto = 9;
static const JswSymPtr jswSymbols_InternalError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_InternalError_proto = 10;
static const JswSymPtr jswSymbols_ReferenceError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_ReferenceError_proto = 11;
static const JswSymPtr jswSymbols_JSON[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_json_parse},
  {6, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_json_stringify}
};
static const unsigned char jswSymbolIndex_JSON = 12;
static const JswSymPtr jswSymbols_Math[] FLASH_SECT = {
  {0, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_E},
  {2, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LN10},
  {7, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LN2},
  {11, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LOG10E},
  {18, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LOG2E},
  {24, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_PI},
  {27, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_SQRT1_2},
  {35, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_SQRT2},
  {41, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_abs},
  {45, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_acos},
  {50, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_asin},
  {55, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_atan},
  {60, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))atan2},
  {66, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))ceil},
  {71, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*3)), (void (*)(void))jswrap_math_clip},
  {76, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_cos},
  {80, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))exp},
  {84, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))floor},
  {90, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))log},
  {94, JSWAT_JSVARFLOAT | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_max},
  {98, JSWAT_JSVARFLOAT | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_min},
  {102, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))jswrap_math_pow},
  {106, JSWAT_JSVARFLOAT, (void (*)(void))gen_jswrap_Math_random},
  {113, JSWAT_JSVAR | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_round},
  {119, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_sin},
  {123, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_sqrt},
  {128, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_tan},
  {132, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))wrapAround}
};
static const unsigned char jswSymbolIndex_Math = 13;
static const JswSymPtr jswSymbols_Modules[] FLASH_SECT = {
  {0, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_modules_addCached},
  {10, JSWAT_JSVAR, (void (*)(void))jswrap_modules_getCached},
  {20, JSWAT_VOID, (void (*)(void))jswrap_modules_removeAllCached},
  {36, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_modules_removeCached}
};
static const unsigned char jswSymbolIndex_Modules = 14;
static const JswSymPtr jswSymbols_Number[] FLASH_SECT = {
  {0, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_MAX_VALUE},
  {10, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_MIN_VALUE},
  {20, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_NEGATIVE_INFINITY},
  {38, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_NaN},
  {42, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_POSITIVE_INFINITY}
};
static const unsigned char jswSymbolIndex_Number = 15;
static const JswSymPtr jswSymbols_Number_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_number_toFixed}
};
static const unsigned char jswSymbolIndex_Number_proto = 16;
static const JswSymPtr jswSymbols_Object_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_object_clone},
  {6, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_emit},
  {11, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_hasOwnProperty},
  {26, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_object_length},
  {33, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_on},
  {36, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_removeAllListeners},
  {55, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_removeListener},
  {70, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_toString},
  {79, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_object_valueOf}
};
static const unsigned char jswSymbolIndex_Object_proto = 17;
static const JswSymPtr jswSymbols_Object[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_assign},
  {7, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_create},
  {14, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_defineProperties},
  {31, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_object_defineProperty},
  {46, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_getOwnPropertyDescriptor},
  {71, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Object_getOwnPropertyNames},
  {91, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_getPrototypeOf},
  {106, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Object_keys},
  {111, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_setPrototypeOf}
};
static const unsigned char jswSymbolIndex_Object = 18;
static const JswSymPtr jswSymbols_Function_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_function_apply_or_call},
  {6, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2)), (void (*)(void))jswrap_function_bind},
  {11, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2)), (void (*)(void))jswrap_function_apply_or_call},
  {16, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_function_replaceWith}
};
static const unsigned char jswSymbolIndex_Function_proto = 19;
static const JswSymPtr jswSymbols_process[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_process_env},
  {4, JSWAT_JSVAR, (void (*)(void))jswrap_process_memory},
  {11, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_process_version}
};
static const unsigned char jswSymbolIndex_process = 20;
static const JswSymPtr jswSymbols_Promise[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_all},
  {4, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_reject},
  {11, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_resolve}
};
static const unsigned char jswSymbolIndex_Promise = 21;
static const JswSymPtr jswSymbols_Promise_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_catch},
  {6, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_promise_then}
};
static const unsigned char jswSymbolIndex_Promise_proto = 22;
static const JswSymPtr jswSymbols_RegExp_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_regexp_exec},
  {5, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_regexp_test}
};
static const unsigned char jswSymbolIndex_RegExp_proto = 23;
static const JswSymPtr jswSymbols_String_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_charAt},
  {7, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_charCodeAt},
  {18, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_String_indexOf},
  {26, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_String_lastIndexOf},
  {38, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_object_length},
  {45, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_string_replace},
  {53, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_string_slice},
  {59, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_split},
  {65, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_string_substr},
  {72, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_string_substring},
  {82, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))gen_jswrap_String_toLowerCase},
  {94, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))gen_jswrap_String_toUpperCase},
  {106, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_string_trim}
};
static const unsigned char jswSymbolIndex_String_proto = 24;
static const JswSymPtr jswSymbols_String[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_fromCharCode}
};
static const unsigned char jswSymbolIndex_String = 25;
static const JswSymPtr jswSymbols_Motor_proto[] FLASH_SECT = {
  {0, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))jswrap_motor_write}
};
static const unsigned char jswSymbolIndex_Motor_proto = 26;
static const JswSymPtr jswSymbols_LED[] FLASH_SECT = {
  {0, JSWAT_VOID, (void (*)(void))jswrap_led_off},
  {4, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_led_set}
};
static const unsigned char jswSymbolIndex_LED = 27;
static const JswSymPtr jswSymbols_Range[] FLASH_SECT = {
  
};
static const unsigned char jswSymbolIndex_Range = 28;
static const JswSymPtr jswSymbols_Range_proto[] FLASH_SECT = {
  {0, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_range_read}
};
static const unsigned char jswSymbolIndex_Range_proto = 29;


FLASH_STR(jswSymbols_global_str, "Array\0ArrayBuffer\0ArrayBufferView\0Boolean\0DataView\0Date\0Error\0Float32Array\0Float64Array\0Function\0HIGH\0Infinity\0Int16Array\0Int32Array\0Int8Array\0InternalError\0JSON\0LED\0LOW\0Math\0Modules\0Motor\0NaN\0Number\0Object\0Promise\0Range\0ReferenceError\0RegExp\0String\0SyntaxError\0TypeError\0Uint16Array\0Uint32Array\0Uint8Array\0Uint8ClampedArray\0arguments\0atob\0btoa\0changeInterval\0clearInterval\0clearTimeout\0decodeURIComponent\0encodeURIComponent\0eval\0getTime\0isNaN\0parseFloat\0parseInt\0process\0require\0setInterval\0setTime\0setTimeout\0");
FLASH_STR(jswSymbols_Array_proto_str, "concat\0every\0fill\0filter\0forEach\0indexOf\0join\0length\0map\0pop\0push\0reduce\0reverse\0shift\0slice\0some\0sort\0splice\0toString\0unshift\0");
FLASH_STR(jswSymbols_Array_str, "isArray\0");
FLASH_STR(jswSymbols_ArrayBufferView_proto_str, "buffer\0byteLength\0byteOffset\0fill\0forEach\0indexOf\0join\0map\0reduce\0reverse\0set\0slice\0sort\0");
FLASH_STR(jswSymbols_DataView_proto_str, "getFloat32\0getFloat64\0getInt16\0getInt32\0getInt8\0getUint16\0getUint32\0getUint8\0setFloat32\0setFloat64\0setInt16\0setInt32\0setInt8\0setUint16\0setUint32\0setUint8\0");
FLASH_STR(jswSymbols_Date_str, "now\0parse\0");
FLASH_STR(jswSymbols_Date_proto_str, "getDate\0getDay\0getFullYear\0getHours\0getMilliseconds\0getMinutes\0getMonth\0getSeconds\0getTime\0getTime\0getTimezoneOffset\0setDate\0setFullYear\0setHours\0setMilliseconds\0setMinutes\0setMonth\0setSeconds\0toISOString\0toString\0toUTCString\0valueOf\0");
FLASH_STR(jswSymbols_Error_proto_str, "toString\0");
FLASH_STR(jswSymbols_SyntaxError_proto_str, "toString\0");
FLASH_STR(jswSymbols_TypeError_proto_str, "toString\0");
FLASH_STR(jswSymbols_InternalError_proto_str, "toString\0");
FLASH_STR(jswSymbols_ReferenceError_proto_str, "toString\0");
FLASH_STR(jswSymbols_JSON_str, "parse\0stringify\0");
FLASH_STR(jswSymbols_Math_str, "E\0LN10\0LN2\0LOG10E\0LOG2E\0PI\0SQRT1_2\0SQRT2\0abs\0acos\0asin\0atan\0atan2\0ceil\0clip\0cos\0exp\0floor\0log\0max\0min\0pow\0random\0round\0sin\0sqrt\0tan\0wrap\0");
FLASH_STR(jswSymbols_Modules_str, "addCached\0getCached\0removeAllCached\0removeCached\0");
FLASH_STR(jswSymbols_Number_str, "MAX_VALUE\0MIN_VALUE\0NEGATIVE_INFINITY\0NaN\0POSITIVE_INFINITY\0");
FLASH_STR(jswSymbols_Number_proto_str, "toFixed\0");
FLASH_STR(jswSymbols_Object_proto_str, "clone\0emit\0hasOwnProperty\0length\0on\0removeAllListeners\0removeListener\0toString\0valueOf\0");
FLASH_STR(jswSymbols_Object_str, "assign\0create\0defineProperties\0defineProperty\0getOwnPropertyDescriptor\0getOwnPropertyNames\0getPrototypeOf\0keys\0setPrototypeOf\0");
FLASH_STR(jswSymbols_Function_proto_str, "apply\0bind\0call\0replaceWith\0");
FLASH_STR(jswSymbols_process_str, "env\0memory\0version\0");
FLASH_STR(jswSymbols_Promise_str, "all\0reject\0resolve\0");
FLASH_STR(jswSymbols_Promise_proto_str, "catch\0then\0");
FLASH_STR(jswSymbols_RegExp_proto_str, "exec\0test\0");
FLASH_STR(jswSymbols_String_proto_str, "charAt\0charCodeAt\0indexOf\0lastIndexOf\0length\0replace\0slice\0split\0substr\0substring\0toLowerCase\0toUpperCase\0trim\0");
FLASH_STR(jswSymbols_String_str, "fromCharCode\0");
FLASH_STR(jswSymbols_Motor_proto_str, "write\0");
FLASH_STR(jswSymbols_LED_str, "off\0set\0");
FLASH_STR(jswSymbols_Range_str, "");
FLASH_STR(jswSymbols_Range_proto_str, "read\0");

const JswSymList jswSymbolTables[] FLASH_SECT = {
  {jswSymbols_global, jswSymbols_global_str, 54},
  {jswSymbols_Array_proto, jswSymbols_Array_proto_str, 20},
  {jswSymbols_Array, jswSymbols_Array_str, 1},
  {jswSymbols_ArrayBufferView_proto, jswSymbols_ArrayBufferView_proto_str, 13},
  {jswSymbols_DataView_proto, jswSymbols_DataView_proto_str, 16},
  {jswSymbols_Date, jswSymbols_Date_str, 2},
  {jswSymbols_Date_proto, jswSymbols_Date_proto_str, 22},
  {jswSymbols_Error_proto, jswSymbols_Error_proto_str, 1},
  {jswSymbols_SyntaxError_proto, jswSymbols_SyntaxError_proto_str, 1},
  {jswSymbols_TypeError_proto, jswSymbols_TypeError_proto_str, 1},
  {jswSymbols_InternalError_proto, jswSymbols_InternalError_proto_str, 1},
  {jswSymbols_ReferenceError_proto, jswSymbols_ReferenceError_proto_str, 1},
  {jswSymbols_JSON, jswSymbols_JSON_str, 2},
  {jswSymbols_Math, jswSymbols_Math_str, 28},
  {jswSymbols_Modules, jswSymbols_Modules_str, 4},
  {jswSymbols_Number, jswSymbols_Number_str, 5},
  {jswSymbols_Number_proto, jswSymbols_Number_proto_str, 1},
  {jswSymbols_Object_proto, jswSymbols_Object_proto_str, 9},
  {jswSymbols_Object, jswSymbols_Object_str, 9},
  {jswSymbols_Function_proto, jswSymbols_Function_proto_str, 4},
  {jswSymbols_process, jswSymbols_process_str, 3},
  {jswSymbols_Promise, jswSymbols_Promise_str, 3},
  {jswSymbols_Promise_proto, jswSymbols_Promise_proto_str, 2},
  {jswSymbols_RegExp_proto, jswSymbols_RegExp_proto_str, 2},
  {jswSymbols_String_proto, jswSymbols_String_proto_str, 13},
  {jswSymbols_String, jswSymbols_String_str, 1},
  {jswSymbols_Motor_proto, jswSymbols_Motor_proto_str, 1},
  {jswSymbols_LED, jswSymbols_LED_str, 2},
  {jswSymbols_Range, jswSymbols_Range_str, 0},
  {jswSymbols_Range_proto, jswSymbols_Range_proto_str, 1},
};


const JswSymList *jswGetSymbolListForConstructorProto(JsVar *constructor) {
  void *constructorPtr = constructor->varData.native.ptr;
  if (constructorPtr==(void*)jswrap_dataview_constructor) return &jswSymbolTables[jswSymbolIndex_DataView_proto];
  if (constructorPtr==(void*)jswrap_date_constructor) return &jswSymbolTables[jswSymbolIndex_Date_proto];
  if (constructorPtr==(void*)jswrap_error_constructor) return &jswSymbolTables[jswSymbolIndex_Error_proto];
  if (constructorPtr==(void*)jswrap_syntaxerror_constructor) return &jswSymbolTables[jswSymbolIndex_SyntaxError_proto];
  if (constructorPtr==(void*)jswrap_typeerror_constructor) return &jswSymbolTables[jswSymbolIndex_TypeError_proto];
  if (constructorPtr==(void*)jswrap_internalerror_constructor) return &jswSymbolTables[jswSymbolIndex_InternalError_proto];
  if (constructorPtr==(void*)jswrap_referenceerror_constructor) return &jswSymbolTables[jswSymbolIndex_ReferenceError_proto];
  if (constructorPtr==(void*)jswrap_promise_constructor) return &jswSymbolTables[jswSymbolIndex_Promise_proto];
  if (constructorPtr==(void*)jswrap_regexp_constructor) return &jswSymbolTables[jswSymbolIndex_RegExp_proto];
  if (constructorPtr==(void*)jswrap_motor_constructor) return &jswSymbolTables[jswSymbolIndex_Motor_proto];
  if (constructorPtr==(void*)jswrap_range_constructor) return &jswSymbolTables[jswSymbolIndex_Range_proto];
  return 0;
}


JsVar *jswFindBuiltInFunction(JsVar *parent, const char *name) {
  JsVar *v;
  if (parent && !jsvIsRoot(parent)) {
    // ------------------------------------------ INSTANCE + STATIC METHODS
    if (jsvIsNativeFunction(parent)) {
      const JswSymList *l = jswGetSymbolListForObject(parent);
      if (l) {
        v = jswBinarySearch(l, parent, name);
        if (v) return v;
      }
    }
    if (jsvIsArray(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Array_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsArrayBuffer(parent) && parent->varData.arraybuffer.type!=ARRAYBUFFERVIEW_ARRAYBUFFER) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsNumeric(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Number_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsFunction(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Function_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsString(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_String_proto], parent, name);
      if (v) return v;
    }
    // ------------------------------------------ INSTANCE METHODS WE MUST CHECK CONSTRUCTOR FOR
    JsVar *proto = jsvIsObject(parent)?jsvSkipNameAndUnLock(jsvFindChildFromString(parent, JSPARSE_INHERITS_VAR, false)):0;
    JsVar *constructor = jsvIsObject(proto)?jsvSkipNameAndUnLock(jsvFindChildFromString(proto, JSPARSE_CONSTRUCTOR_VAR, false)):0;
    jsvUnLock(proto);
    if (constructor && jsvIsNativeFunction(constructor)) {
      const JswSymList *l = jswGetSymbolListForConstructorProto(constructor);
      jsvUnLock(constructor);
      if (l) {
        v = jswBinarySearch(l, parent, name);
        if (v) return v;
      }
    } else {
      jsvUnLock(constructor);
    }
    // ------------------------------------------ METHODS ON OBJECT
    v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Object_proto], parent, name);
    if (v) return v;
  } else { /* if (!parent) */
    // ------------------------------------------ FUNCTIONS
    // Handle pin names - eg LED1 or D5 (this is hardcoded in build_jsfunctions.py)
    Pin pin = jshGetPinFromString(name);
    if (pin != PIN_UNDEFINED) {
      return jsvNewFromPin(pin);
    }
    return jswBinarySearch(&jswSymbolTables[jswSymbolIndex_global], parent, name);
  }
  return 0;
}


const JswSymList *jswGetSymbolListForObject(JsVar *parent) {
  if (jsvIsNativeFunction(parent)) {
    if ((void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) return &jswSymbolTables[jswSymbolIndex_Array];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_date_constructor) return &jswSymbolTables[jswSymbolIndex_Date];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_JSON_JSON) return &jswSymbolTables[jswSymbolIndex_JSON];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Math_Math) return &jswSymbolTables[jswSymbolIndex_Math];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Modules_Modules) return &jswSymbolTables[jswSymbolIndex_Modules];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) return &jswSymbolTables[jswSymbolIndex_Number];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_object_constructor) return &jswSymbolTables[jswSymbolIndex_Object];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_process_process) return &jswSymbolTables[jswSymbolIndex_process];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_promise_constructor) return &jswSymbolTables[jswSymbolIndex_Promise];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) return &jswSymbolTables[jswSymbolIndex_String];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_LED_LED) return &jswSymbolTables[jswSymbolIndex_LED];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_range_constructor) return &jswSymbolTables[jswSymbolIndex_Range];
  }
  if (parent==execInfo.root) return &jswSymbolTables[jswSymbolIndex_global];
  return 0;
}


const JswSymList *jswGetSymbolListForObjectProto(JsVar *parent) {
  if (jsvIsNativeFunction(parent)) {
    if ((void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) return &jswSymbolTables[jswSymbolIndex_Array_proto];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_ArrayBufferView_ArrayBufferView) return &jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) return &jswSymbolTables[jswSymbolIndex_Number_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_function_constructor) return &jswSymbolTables[jswSymbolIndex_Function_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) return &jswSymbolTables[jswSymbolIndex_String_proto];
  }
  JsVar *constructor = jsvIsObject(parent)?jsvSkipNameAndUnLock(jsvFindChildFromString(parent, JSPARSE_CONSTRUCTOR_VAR, false)):0;
  if (constructor && jsvIsNativeFunction(constructor)) {
    const JswSymList *l = jswGetSymbolListForConstructorProto(constructor);
    jsvUnLock(constructor);
    if (l) return l;
  }
  if (jsvIsArray(parent)) return &jswSymbolTables[jswSymbolIndex_Array_proto];
  if (jsvIsArrayBuffer(parent) && parent->varData.arraybuffer.type!=ARRAYBUFFERVIEW_ARRAYBUFFER) return &jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto];
  if (jsvIsNumeric(parent)) return &jswSymbolTables[jswSymbolIndex_Number_proto];
  if (jsvIsFunction(parent)) return &jswSymbolTables[jswSymbolIndex_Function_proto];
  if (jsvIsString(parent)) return &jswSymbolTables[jswSymbolIndex_String_proto];
  return &jswSymbolTables[jswSymbolIndex_Object_proto];
}


bool jswIsBuiltInObject(const char *name) {
  return
strcmp(name, "Array")==0 ||
    strcmp(name, "ArrayBuffer")==0 ||
    strcmp(name, "ArrayBufferView")==0 ||
    strcmp(name, "Uint8Array")==0 ||
    strcmp(name, "Uint8ClampedArray")==0 ||
    strcmp(name, "Int8Array")==0 ||
    strcmp(name, "Uint16Array")==0 ||
    strcmp(name, "Int16Array")==0 ||
    strcmp(name, "Uint32Array")==0 ||
    strcmp(name, "Int32Array")==0 ||
    strcmp(name, "Float32Array")==0 ||
    strcmp(name, "Float64Array")==0 ||
    strcmp(name, "DataView")==0 ||
    strcmp(name, "Date")==0 ||
    strcmp(name, "Error")==0 ||
    strcmp(name, "SyntaxError")==0 ||
    strcmp(name, "TypeError")==0 ||
    strcmp(name, "InternalError")==0 ||
    strcmp(name, "ReferenceError")==0 ||
    strcmp(name, "Function")==0 ||
    strcmp(name, "JSON")==0 ||
    strcmp(name, "Math")==0 ||
    strcmp(name, "Modules")==0 ||
    strcmp(name, "Number")==0 ||
    strcmp(name, "Object")==0 ||
    strcmp(name, "Boolean")==0 ||
    strcmp(name, "process")==0 ||
    strcmp(name, "Promise")==0 ||
    strcmp(name, "RegExp")==0 ||
    strcmp(name, "String")==0 ||
    strcmp(name, "Motor")==0 ||
    strcmp(name, "LED")==0 ||
    strcmp(name, "Range")==0;
}


void *jswGetBuiltInLibrary(const char *name) {
  return 0;
}


/** Given a variable, return the basic object name of it */
const char *jswGetBasicObjectName(JsVar *var) {
  if (jsvIsFunction(var)) return "Function";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT32) return "Int32Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==(ARRAYBUFFERVIEW_UINT8|ARRAYBUFFERVIEW_CLAMPED)) return "Uint8ClampedArray";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT32) return "Uint32Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_ARRAYBUFFER) return "ArrayBuffer";
  if (jsvIsObject(var)) return "Object";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT8) return "Uint8Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT16) return "Uint16Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_FLOAT64) return "Float64Array";
  if (jsvIsNumeric(var)) return "Number";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT8) return "Int8Array";
  if (jsvIsArray(var)) return "Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT16) return "Int16Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_FLOAT32) return "Float32Array";
  if (jsvIsString(var)) return "String";
  return 0;
}


/** Given the name of a Basic Object, eg, Uint8Array, String, etc. Return the prototype object's name - or 0. */
const char *jswGetBasicObjectPrototypeName(const char *objectName) {
  if (!strcmp(objectName, "Uint8Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint8ClampedArray")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int8Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint16Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int16Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Float32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Float64Array")) return "ArrayBufferView";
  return strcmp(objectName,"Object") ? "Object" : 0;
}


/** Tasks to run on Idle. Returns true if either one of the tasks returned true (eg. they're doing something and want to avoid sleeping) */
bool jswIdle() {
  bool wasBusy = false;
  return wasBusy;
}


/** Tasks to run on Initialisation */
void jswInit() {
}


/** Tasks to run on Deinitialisation */
void jswKill() {
}
/** If we have a built-in module with the given name, return the module's contents - or 0 */
const char *jswGetBuiltInJSLibrary(const char *name) {
  return 0;
}


const char *jswGetBuiltInLibraryNames() {
  return "";
}


