// Automatically generated wrapper file 
// Generated by scripts/build_jswrapper.py

#include "jswrapper.h"
#include "jsnative.h"
#include "src/jswrap_array.h"
#include "src/jswrap_arraybuffer.h"
#include "src/jswrap_dataview.h"
#include "src/jswrap_date.h"
#include "src/jswrap_error.h"
#include "src/jswrap_espruino.h"
#include "src/jswrap_flash.h"
#include "src/jswrap_functions.h"
#include "src/jswrap_interactive.h"
#include "src/jswrap_io.h"
#include "src/jswrap_json.h"
#include "src/jswrap_modules.h"
#include "src/jswrap_pin.h"
#include "src/jswrap_number.h"
#include "src/jswrap_object.h"
#include "src/jswrap_onewire.h"
#include "src/jswrap_pipe.h"
#include "src/jswrap_process.h"
#include "src/jswrap_promise.h"
#include "src/jswrap_regexp.h"
#include "src/jswrap_serial.h"
#include "src/jswrap_spi_i2c.h"
#include "src/jswrap_stream.h"
#include "src/jswrap_string.h"
#include "src/jswrap_waveform.h"
#include "libs/math/jswrap_math.h"
#include "libs/graphics/jswrap_graphics.h"
#include "libs/network/jswrap_net.h"
#include "libs/network/http/jswrap_http.h"
#include "libs/network/js/jswrap_jsnetwork.h"
#include "libs/bluetooth/jswrap_bluetooth.h"
#include "libs/neopixel/jswrap_neopixel.h"
#include "platform_config.h"

#include "js/devices/jswrap_port.h"


// -----------------------------------------------------------------------------------------
// ----------------------------------------------------------------- AUTO-GENERATED WRAPPERS
// -----------------------------------------------------------------------------------------

static JsVar* gen_jswrap_Array_pop(JsVar *parent) {
  return jsvArrayPop(parent);
}

static bool gen_jswrap_Array_isArray(JsVar* var) {
  return jsvIsArray(var);
}

static JsVar* gen_jswrap_Uint8Array_Uint8Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT8, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint8ClampedArray_Uint8ClampedArray(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT8|ARRAYBUFFERVIEW_CLAMPED, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int8Array_Int8Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT8, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint16Array_Uint16Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT16, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int16Array_Int16Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT16, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Uint32Array_Uint32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_UINT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Int32Array_Int32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_INT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Float32Array_Float32Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_FLOAT32, arr, byteOffset, length);
}

static JsVar* gen_jswrap_Float64Array_Float64Array(JsVar* arr, JsVarInt byteOffset, JsVarInt length) {
  return jswrap_typedarray_constructor(ARRAYBUFFERVIEW_FLOAT64, arr, byteOffset, length);
}

static JsVar* gen_jswrap_ArrayBufferView_buffer(JsVar *parent) {
  return jsvLock(jsvGetFirstChild(parent));
}

static JsVarInt gen_jswrap_ArrayBufferView_byteLength(JsVar *parent) {
  return (JsVarInt)(parent->varData.arraybuffer.length * JSV_ARRAYBUFFER_GET_SIZE(parent->varData.arraybuffer.type));
}

static JsVarInt gen_jswrap_ArrayBufferView_byteOffset(JsVar *parent) {
  return parent->varData.arraybuffer.byteOffset;
}

static JsVar* gen_jswrap_DataView_getFloat32(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_FLOAT32, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getFloat64(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_FLOAT64, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getInt8(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_INT8, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getInt16(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_INT16, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getInt32(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_INT32, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getUint8(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_UINT8, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getUint16(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_UINT16, byteOffset, littleEndian);
}

static JsVar* gen_jswrap_DataView_getUint32(JsVar *parent, JsVarInt byteOffset, bool littleEndian) {
  return jswrap_dataview_get(parent, ARRAYBUFFERVIEW_UINT32, byteOffset, littleEndian);
}

static void gen_jswrap_DataView_setFloat32(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_FLOAT32, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setFloat64(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_FLOAT64, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setInt8(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_INT8, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setInt16(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_INT16, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setInt32(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_INT32, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setUint8(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_UINT8, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setUint16(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_UINT16, byteOffset, value, littleEndian);
}

static void gen_jswrap_DataView_setUint32(JsVar *parent, JsVarInt byteOffset, JsVar* value, bool littleEndian) {
  jswrap_dataview_set(parent, ARRAYBUFFERVIEW_UINT32, byteOffset, value, littleEndian);
}

//static JsVarFloat gen_jswrap_E_getTemperature() {
//  return jshReadTemperature();
//}
//
//static JsVarFloat gen_jswrap_E_getAnalogVRef() {
//  return jshReadVRef();
//}

static JsVar* gen_jswrap_global() {
  return jsvLockAgain(execInfo.root);
}

static void gen_jswrap_dump() {
  //jsiDumpState((vcbprintf_callback)jsiConsolePrintString, 0);
}

static void gen_jswrap_load() {
  jsiStatus|=JSIS_TODO_FLASH_LOAD;;
}

static void gen_jswrap_save() {
  jsiStatus|=JSIS_TODO_FLASH_SAVE;;
}

static JsVarFloat gen_jswrap_getTime() {
  return 0; //(JsVarFloat)jshGetSystemTime() / (JsVarFloat)jshGetTimeFromMilliseconds(1000);
}

static JsVar* gen_jswrap_peek8(JsVarInt addr, JsVarInt count) {
  return 0; //jswrap_io_peek(addr,count,1);
}

static void gen_jswrap_poke8(JsVarInt addr, JsVar* value) {
  //jswrap_io_poke(addr,value,1);
}

static JsVar* gen_jswrap_peek16(JsVarInt addr, JsVarInt count) {
  return 0; //jswrap_io_peek(addr,count,2);
}

static void gen_jswrap_poke16(JsVarInt addr, JsVar* value) {
  //jswrap_io_poke(addr,value,2);
}

static JsVar* gen_jswrap_peek32(JsVarInt addr, JsVarInt count) {
  return 0; //jswrap_io_peek(addr,count,4);
}

static void gen_jswrap_poke32(JsVarInt addr, JsVar* value) {
  //jswrap_io_poke(addr,value,4);
}

static JsVarFloat gen_jswrap_NaN() {
  return NAN;
}

static JsVarFloat gen_jswrap_Infinity() {
  return INFINITY;
}

static JsVarFloat gen_jswrap_Number_NaN() {
  return NAN;
}

static JsVarFloat gen_jswrap_Number_MAX_VALUE() {
  return DBL_MAX;
}

static JsVarFloat gen_jswrap_Number_MIN_VALUE() {
  return DBL_MIN;
}

static JsVarFloat gen_jswrap_Number_NEGATIVE_INFINITY() {
  return -INFINITY;
}

static JsVarFloat gen_jswrap_Number_POSITIVE_INFINITY() {
  return INFINITY;
}

static int gen_jswrap_HIGH() {
  return 1;
}

static int gen_jswrap_LOW() {
  return 0;
}

static JsVar* gen_jswrap_Object_keys(JsVar* object) {
  return jswrap_object_keys_or_property_names(object, false, false);
}

static JsVar* gen_jswrap_Object_getOwnPropertyNames(JsVar* object) {
  return jswrap_object_keys_or_property_names(object, true, false);
}

static JsVar* gen_jswrap_process_version() {
  return jsvNewFromString(JS_VERSION);
}

static JsVar* gen_jswrap_LoopbackA() {
  return jspNewObject("LoopbackA", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_LoopbackB() {
  return jspNewObject("LoopbackB", "Serial") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
}

static JsVar* gen_jswrap_Port_find() {
  return jsvNewFromString("port");
}

//static void gen_jswrap_Serial_setConsole(JsVar *parent, bool force) {
//}
//
//static JsVar* gen_jswrap_SPI1() {
//  return jspNewObject("SPI1", "SPI") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
//}
//
//static JsVar* gen_jswrap_SPI2() {
//  return jspNewObject("SPI2", "SPI") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
//}
//
//static JsVar* gen_jswrap_SPI3() {
//  return jspNewObject("SPI3", "SPI") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
//}
//
//static JsVar* gen_jswrap_SPI_find(Pin pin) {
//  return jshGetDeviceObjectFor(JSH_SPI1, JSH_SPIMAX, pin);
//}
//
//static JsVar* gen_jswrap_I2C_find(Pin pin) {
//  return jshGetDeviceObjectFor(JSH_I2C1, JSH_I2CMAX, pin);
//}
//
//static JsVar* gen_jswrap_I2C1() {
//  return jspNewObject("I2C1", "I2C") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
//}
//
//static JsVar* gen_jswrap_I2C2() {
//  return jspNewObject("I2C2", "I2C") /* needs JSWAT_EXECUTE_IMMEDIATELY */;
//}

static int gen_jswrap_String_indexOf(JsVar *parent, JsVar* substring, JsVar* fromIndex) {
  return jswrap_string_indexOf(parent, substring, fromIndex, false);
}

static int gen_jswrap_String_lastIndexOf(JsVar *parent, JsVar* substring, JsVar* fromIndex) {
  return jswrap_string_indexOf(parent, substring, fromIndex, true);
}

static JsVar* gen_jswrap_String_toLowerCase(JsVar *parent) {
  return jswrap_string_toUpperLowerCase(parent, false);
}

static JsVar* gen_jswrap_String_toUpperCase(JsVar *parent) {
  return jswrap_string_toUpperLowerCase(parent, true);
}

static JsVarFloat gen_jswrap_Math_E() {
  return 2.718281828459045;
}

static JsVarFloat gen_jswrap_Math_PI() {
  return PI;
}

static JsVarFloat gen_jswrap_Math_LN2() {
  return 0.6931471805599453;
}

static JsVarFloat gen_jswrap_Math_LN10() {
  return 2.302585092994046;
}

static JsVarFloat gen_jswrap_Math_LOG2E() {
  return 1.4426950408889634;
}

static JsVarFloat gen_jswrap_Math_LOG10E() {
  return 0.4342944819032518;
}

static JsVarFloat gen_jswrap_Math_SQRT2() {
  return 1.4142135623730951;
}

static JsVarFloat gen_jswrap_Math_SQRT1_2() {
  return 0.7071067811865476;
}

static JsVarFloat gen_jswrap_Math_acos(JsVarFloat x) {
  return jswrap_math_atan(jswrap_math_sqrt(1-x*x) / x);
}

static JsVarFloat gen_jswrap_Math_asin(JsVarFloat x) {
  return jswrap_math_atan(x / jswrap_math_sqrt(1-x*x));
}

static JsVarFloat gen_jswrap_Math_cos(JsVarFloat theta) {
  return jswrap_math_sin(theta + (PI/2));
}

static JsVarFloat gen_jswrap_Math_random() {
  return (JsVarFloat)rand() / (JsVarFloat)RAND_MAX;
}

static JsVarFloat gen_jswrap_Math_tan(JsVarFloat theta) {
  return jswrap_math_sin(theta) / jswrap_math_sin(theta+(PI/2));
}

static JsVarFloat gen_jswrap_Math_min(JsVar* args) {
  return jswrap_math_minmax(args, false);
}

static JsVarFloat gen_jswrap_Math_max(JsVar* args) {
  return jswrap_math_minmax(args, true);
}

static JsVar* gen_jswrap_ArrayBufferView_ArrayBufferView() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_E_E() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Flash_Flash() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_JSON_JSON() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Modules_Modules() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_fs_fs() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_process_process() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Serial_Serial() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Math_Math() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Graphics_Graphics() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_url_url() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_net_net() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Server_Server() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_Socket_Socket() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_dgram_dgram() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_http_http() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpSrv_httpSrv() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpSRq_httpSRq() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpSRs_httpSRs() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpCRq_httpCRq() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_httpCRs_httpCRs() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_NetworkJS_NetworkJS() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_NRF_NRF() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_BluetoothDevice_BluetoothDevice() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_BluetoothRemoteGATTCharacteristic_BluetoothRemoteGATTCharacteristic() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_BluetoothRemoteGATTServer_BluetoothRemoteGATTServer() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_BluetoothRemoteGATTService_BluetoothRemoteGATTService() {
  return jsvNewWithFlags(JSV_OBJECT);
}

static JsVar* gen_jswrap_neopixel_neopixel() {
  return jsvNewWithFlags(JSV_OBJECT);
}

// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------


// Binary search coded to allow for JswSyms to be in flash on the esp8266 where they require
// word accesses
JsVar *jswBinarySearch(const JswSymList *symbolsPtr, JsVar *parent, const char *name) {
  uint8_t symbolCount = READ_FLASH_UINT8(&symbolsPtr->symbolCount);
  int searchMin = 0;
  int searchMax = symbolCount - 1;
  while (searchMin <= searchMax) {
    int idx = (searchMin+searchMax) >> 1;
    const JswSymPtr *sym = &symbolsPtr->symbols[idx];
    unsigned short strOffset = READ_FLASH_UINT16(&sym->strOffset);
    int cmp = FLASH_STRCMP(name, &symbolsPtr->symbolChars[strOffset]);
    if (cmp==0) {
      unsigned short functionSpec = READ_FLASH_UINT16(&sym->functionSpec);
      if ((functionSpec & JSWAT_EXECUTE_IMMEDIATELY_MASK) == JSWAT_EXECUTE_IMMEDIATELY)
        return jsnCallFunction(sym->functionPtr, functionSpec, parent, 0, 0);
      return jsvNewNativeFunction(sym->functionPtr, functionSpec);
    } else {
      if (cmp<0) {
        // searchMin is the same
        searchMax = idx-1;
      } else {
        searchMin = idx+1;
        // searchMax is the same
      }
    }
  }
  return 0;
}


// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------


#ifdef ESP8266
#define FLASH_SECT __attribute__((section(".irom.literal2"))) __attribute__((aligned(4)))
#else
#define FLASH_SECT
#endif

static const JswSymPtr jswSymbols_global[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_constructor},
  {6, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_arraybuffer_constructor},
  {18, JSWAT_JSVAR, (void (*)(void))gen_jswrap_ArrayBufferView_ArrayBufferView},
  {68, JSWAT_JSVAR, (void (*)(void))gen_jswrap_BluetoothDevice_BluetoothDevice},
  {84, JSWAT_JSVAR, (void (*)(void))gen_jswrap_BluetoothRemoteGATTCharacteristic_BluetoothRemoteGATTCharacteristic},
  {118, JSWAT_JSVAR, (void (*)(void))gen_jswrap_BluetoothRemoteGATTServer_BluetoothRemoteGATTServer},
  {144, JSWAT_JSVAR, (void (*)(void))gen_jswrap_BluetoothRemoteGATTService_BluetoothRemoteGATTService},
  {171, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_boolean_constructor},
  {179, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))jswrap_dataview_constructor},
  {188, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_constructor},
  {193, JSWAT_JSVAR, (void (*)(void))gen_jswrap_E_E},
  {195, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_error_constructor},
  {201, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Float32Array_Float32Array},
  {214, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Float64Array_Float64Array},
  {227, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_function_constructor},
  {236, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Graphics_Graphics},
  {245, JSWAT_INT32 | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_HIGH},
  {264, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Infinity},
  {273, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Int16Array_Int16Array},
  {284, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Int32Array_Int32Array},
  {295, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Int8Array_Int8Array},
  {305, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_internalerror_constructor},
  {319, JSWAT_JSVAR, (void (*)(void))gen_jswrap_JSON_JSON},
  {348, JSWAT_INT32 | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_LOW},
  {352, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_LoopbackA},
  {362, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_LoopbackB},
  {372, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Math_Math},
  {377, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Modules_Modules},
  {385, JSWAT_JSVAR, (void (*)(void))gen_jswrap_NRF_NRF},
  {389, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_NaN},
  {393, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_number_constructor},
  {400, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_constructor},
  {419, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_constructor},
  {427, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_referenceerror_constructor},
  {442, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_regexp_constructor},
  {449, JSWAT_VOID, (void (*)(void))jswrap_port_constructor},
  {483, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Server_Server},
  {490, JSWAT_JSVAR, (void (*)(void))gen_jswrap_Socket_Socket},
  {497, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_constructor},
  {504, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_syntaxerror_constructor},
  {516, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_typeerror_constructor},
  {526, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint16Array_Uint16Array},
  {538, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint32Array_Uint32Array},
  {550, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint8Array_Uint8Array},
  {561, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_INT32 << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_Uint8ClampedArray_Uint8ClampedArray},
  {611, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_arguments},
  {621, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_atob},
  {626, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_btoa},
  {761, JSWAT_VOID, (void (*)(void))gen_jswrap_dump},
  {795, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_eval},
  {832, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_global},
  {879, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_isNaN},
  {885, JSWAT_VOID, (void (*)(void))gen_jswrap_load},
  {890, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_parseFloat},
  {901, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_parseInt},
  {910, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_peek16},
  {917, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_peek32},
  {924, JSWAT_JSVAR | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_peek8},
  {938, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_poke16},
  {945, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_poke32},
  {952, JSWAT_VOID | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_poke8},
  {964, JSWAT_JSVAR, (void (*)(void))gen_jswrap_process_process},
  {972, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_require},
  {986, JSWAT_VOID, (void (*)(void))gen_jswrap_save},
  {1094, JSWAT_JSVAR, (void (*)(void))gen_jswrap_url_url}
};
static const unsigned char jswSymbolIndex_global = 0;
static const JswSymPtr jswSymbols_Array_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_concat},
  {7, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_every},
  {13, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_array_fill},
  {18, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_filter},
  {25, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_forEach},
  {33, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_indexOf},
  {41, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_join},
  {46, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_object_length},
  {53, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_map},
  {57, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))gen_jswrap_Array_pop},
  {61, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_push},
  {66, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_reduce},
  {73, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_array_reverse},
  {81, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_array_shift},
  {87, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_slice},
  {93, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_some},
  {98, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_sort},
  {103, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*3)), (void (*)(void))jswrap_array_splice},
  {110, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_toString},
  {119, JSWAT_INT32 | JSWAT_THIS_ARG | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_unshift}
};
static const unsigned char jswSymbolIndex_Array_proto = 1;
static const JswSymPtr jswSymbols_Array[] FLASH_SECT = {
  {0, JSWAT_BOOL | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Array_isArray}
};
static const unsigned char jswSymbolIndex_Array = 2;
static const JswSymPtr jswSymbols_ArrayBufferView_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_ArrayBufferView_buffer},
  {7, JSWAT_INT32 | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_ArrayBufferView_byteLength},
  {18, JSWAT_INT32 | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_ArrayBufferView_byteOffset},
  {29, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_array_fill},
  {34, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_forEach},
  {42, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_indexOf},
  {50, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_join},
  {55, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_arraybufferview_map},
  {59, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_reduce},
  {66, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_array_reverse},
  {74, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_INT32 << (JSWAT_BITS*2)), (void (*)(void))jswrap_arraybufferview_set},
  {78, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_array_slice},
  {84, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_array_sort}
};
static const unsigned char jswSymbolIndex_ArrayBufferView_proto = 3;
static const JswSymPtr jswSymbols_DataView_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getFloat32},
  {11, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getFloat64},
  {22, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getInt16},
  {31, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getInt32},
  {40, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getInt8},
  {48, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getUint16},
  {58, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getUint32},
  {68, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_BOOL << (JSWAT_BITS*2)), (void (*)(void))gen_jswrap_DataView_getUint8},
  {77, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setFloat32},
  {88, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setFloat64},
  {99, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setInt16},
  {108, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setInt32},
  {117, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setInt8},
  {125, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setUint16},
  {135, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setUint32},
  {145, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_BOOL << (JSWAT_BITS*3)), (void (*)(void))gen_jswrap_DataView_setUint8}
};
static const unsigned char jswSymbolIndex_DataView_proto = 4;
static const JswSymPtr jswSymbols_Date[] FLASH_SECT = {
  {0, JSWAT_JSVARFLOAT, (void (*)(void))jswrap_date_now},
  {4, JSWAT_JSVARFLOAT | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_parse}
};
static const unsigned char jswSymbolIndex_Date = 5;
static const JswSymPtr jswSymbols_Date_proto[] FLASH_SECT = {
  {0, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getDate},
  {8, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getDay},
  {15, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getFullYear},
  {27, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getHours},
  {36, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getMilliseconds},
  {52, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getMinutes},
  {63, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getMonth},
  {72, JSWAT_INT32 | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getSeconds},
  {83, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getTime},
  {91, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_setTime},
  {99, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getTimezoneOffset},
  {117, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_setDate},
  {125, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_date_setFullYear},
  {137, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)) | (JSWAT_JSVAR << (JSWAT_BITS*4)), (void (*)(void))jswrap_date_setHours},
  {146, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_date_setMilliseconds},
  {162, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_date_setMinutes},
  {173, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_date_setMonth},
  {182, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_date_setSeconds},
  {193, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_toISOString},
  {205, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_toString},
  {214, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_toUTCString},
  {226, JSWAT_JSVARFLOAT | JSWAT_THIS_ARG, (void (*)(void))jswrap_date_getTime}
};
static const unsigned char jswSymbolIndex_Date_proto = 6;
static const JswSymPtr jswSymbols_Error_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_Error_proto = 7;
static const JswSymPtr jswSymbols_SyntaxError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_SyntaxError_proto = 8;
static const JswSymPtr jswSymbols_TypeError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_TypeError_proto = 9;
static const JswSymPtr jswSymbols_InternalError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_InternalError_proto = 10;
static const JswSymPtr jswSymbols_ReferenceError_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_error_toString}
};
static const unsigned char jswSymbolIndex_ReferenceError_proto = 11;

static const JswSymPtr jswSymbols_JSON[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_json_parse},
  {6, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_json_stringify}
};
static const unsigned char jswSymbolIndex_JSON = 15;
static const JswSymPtr jswSymbols_Modules[] FLASH_SECT = {
  {0, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_modules_addCached},
  {10, JSWAT_JSVAR, (void (*)(void))jswrap_modules_getCached},
  {20, JSWAT_VOID, (void (*)(void))jswrap_modules_removeAllCached},
  {36, JSWAT_VOID | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_modules_removeCached}
};
static const unsigned char jswSymbolIndex_Modules = 16;

static const JswSymPtr jswSymbols_Number[] FLASH_SECT = {
  {0, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_MAX_VALUE},
  {10, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_MIN_VALUE},
  {20, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_NEGATIVE_INFINITY},
  {38, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_NaN},
  {42, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Number_POSITIVE_INFINITY}
};
static const unsigned char jswSymbolIndex_Number = 18;
static const JswSymPtr jswSymbols_Number_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_INT32 << (JSWAT_BITS*1)), (void (*)(void))jswrap_number_toFixed}
};
static const unsigned char jswSymbolIndex_Number_proto = 19;
static const JswSymPtr jswSymbols_Object_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_object_clone},
  {6, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_emit},
  {11, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_hasOwnProperty},
  {26, JSWAT_JSVAR | JSWAT_THIS_ARG | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_object_length},
  {33, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_on},
  {36, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_removeAllListeners},
  {55, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_removeListener},
  {70, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_toString},
  {79, JSWAT_JSVAR | JSWAT_THIS_ARG, (void (*)(void))jswrap_object_valueOf}
};
static const unsigned char jswSymbolIndex_Object_proto = 20;
static const JswSymPtr jswSymbols_Object[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_assign},
  {7, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_create},
  {14, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_defineProperties},
  {31, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)) | (JSWAT_JSVAR << (JSWAT_BITS*3)), (void (*)(void))jswrap_object_defineProperty},
  {46, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_getOwnPropertyDescriptor},
  {71, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Object_getOwnPropertyNames},
  {91, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_object_getPrototypeOf},
  {106, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Object_keys},
  {111, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_object_setPrototypeOf}
};
static const unsigned char jswSymbolIndex_Object = 21;
static const JswSymPtr jswSymbols_Function_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_function_apply_or_call},
  {6, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2)), (void (*)(void))jswrap_function_bind},
  {11, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*2)), (void (*)(void))jswrap_function_apply_or_call},
  {16, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_function_replaceWith}
};
static const unsigned char jswSymbolIndex_Function_proto = 22;

static const JswSymPtr jswSymbols_process[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))jswrap_process_env},
  {4, JSWAT_JSVAR, (void (*)(void))jswrap_process_memory},
  {11, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_process_version}
};
static const unsigned char jswSymbolIndex_process = 25;
static const JswSymPtr jswSymbols_Promise[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_all},
  {4, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_reject},
  {11, JSWAT_JSVAR | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_resolve}
};
static const unsigned char jswSymbolIndex_Promise = 26;
static const JswSymPtr jswSymbols_Promise_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_promise_catch},
  {6, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)) | (JSWAT_JSVAR << (JSWAT_BITS*2)), (void (*)(void))jswrap_promise_then}
};
static const unsigned char jswSymbolIndex_Promise_proto = 27;
static const JswSymPtr jswSymbols_RegExp_proto[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_regexp_exec},
  {5, JSWAT_BOOL | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_regexp_test}
};
static const unsigned char jswSymbolIndex_RegExp_proto = 28;

static const JswSymPtr jswSymbols_Port[] FLASH_SECT = {
  {0, JSWAT_JSVAR | JSWAT_EXECUTE_IMMEDIATELY , (void (*)(void))gen_jswrap_Port_find}
};
static const unsigned char jswSymbolIndex_Port = 31;

static const JswSymPtr jswSymbols_Port_proto[] FLASH_SECT = {
  {5, JSWAT_VOID | JSWAT_THIS_ARG | (JSWAT_JSVAR << (JSWAT_BITS*1)), (void (*)(void))jswrap_port_set}
};
static const unsigned char jswSymbolIndex_Port_proto = 32;

static const unsigned char jswSymbolIndex_String_proto = 35;
static const JswSymPtr jswSymbols_String[] FLASH_SECT = {
  {0, JSWAT_JSVAR | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))jswrap_string_fromCharCode}
};
static const unsigned char jswSymbolIndex_String = 36;

static const JswSymPtr jswSymbols_Math[] FLASH_SECT = {
  {0, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_E},
  {2, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LN10},
  {7, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LN2},
  {11, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LOG10E},
  {18, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_LOG2E},
  {24, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_PI},
  {27, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_SQRT1_2},
  {35, JSWAT_JSVARFLOAT | JSWAT_EXECUTE_IMMEDIATELY, (void (*)(void))gen_jswrap_Math_SQRT2},
  {41, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_abs},
  {45, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_acos},
  {50, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_asin},
  {55, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_atan},
  {60, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))atan2},
  {66, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))ceil},
  {71, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*3)), (void (*)(void))jswrap_math_clip},
  {76, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_cos},
  {80, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))exp},
  {84, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))floor},
  {90, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))log},
  {94, JSWAT_JSVARFLOAT | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_max},
  {98, JSWAT_JSVARFLOAT | (JSWAT_ARGUMENT_ARRAY << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_min},
  {102, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))jswrap_math_pow},
  {106, JSWAT_JSVARFLOAT, (void (*)(void))gen_jswrap_Math_random},
  {113, JSWAT_JSVAR | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_round},
  {119, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_sin},
  {123, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))jswrap_math_sqrt},
  {128, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)), (void (*)(void))gen_jswrap_Math_tan},
  {132, JSWAT_JSVARFLOAT | (JSWAT_JSVARFLOAT << (JSWAT_BITS*1)) | (JSWAT_JSVARFLOAT << (JSWAT_BITS*2)), (void (*)(void))wrapAround}
};
static const unsigned char jswSymbolIndex_Math = 38;

FLASH_STR(jswSymbols_global_str, "Array\0ArrayBuffer\0ArrayBufferView\0Bluetooth\0BluetoothDevice\0BluetoothRemoteGATTCharacteristic\0BluetoothRemoteGATTServer\0BluetoothRemoteGATTService\0Boolean\0DataView\0Date\0E\0Error\0Float32Array\0Float64Array\0Function\0Graphics\0HIGH\0Infinity\0Int16Array\0Int32Array\0Int8Array\0InternalError\0JSON\0LOW\0LoopbackA\0LoopbackB\0Math\0Modules\0NRF\0NaN\0Number\0Object\0Promise\0ReferenceError\0RegExp\0Port\0Serial\0Serial1\0Server\0Socket\0String\0SyntaxError\0TypeError\0Uint16Array\0Uint32Array\0Uint8Array\0Uint8ClampedArray\0Waveform\0analogRead\0analogWrite\0arguments\0atob\0btoa\0changeInterval\0clearInterval\0clearTimeout\0clearWatch\0console\0decodeURIComponent\0dgramSocket\0digitalPulse\0digitalRead\0digitalWrite\0dump\0echo\0edit\0encodeURIComponent\0eval\0fs\0getPinMode\0getSerial\0getTime\0global\0httpCRq\0httpCRs\0httpSRq\0httpSRs\0httpSrv\0isNaN\0load\0parseFloat\0parseInt\0peek16\0peek32\0peek8\0pinMode\0poke16\0poke32\0poke8\0print\0process\0require\0reset\0save\0setBusyIndicator\0setDeepSleep\0setInterval\0setSleepIndicator\0setTime\0setTimeout\0setWatch\0shiftOut\0trace\0url\0");
FLASH_STR(jswSymbols_Array_proto_str, "concat\0every\0fill\0filter\0forEach\0indexOf\0join\0length\0map\0pop\0push\0reduce\0reverse\0shift\0slice\0some\0sort\0splice\0toString\0unshift\0");
FLASH_STR(jswSymbols_Array_str, "isArray\0");
FLASH_STR(jswSymbols_ArrayBufferView_proto_str, "buffer\0byteLength\0byteOffset\0fill\0forEach\0indexOf\0join\0map\0reduce\0reverse\0set\0slice\0sort\0");
FLASH_STR(jswSymbols_DataView_proto_str, "getFloat32\0getFloat64\0getInt16\0getInt32\0getInt8\0getUint16\0getUint32\0getUint8\0setFloat32\0setFloat64\0setInt16\0setInt32\0setInt8\0setUint16\0setUint32\0setUint8\0");
FLASH_STR(jswSymbols_Date_str, "now\0parse\0");
FLASH_STR(jswSymbols_Date_proto_str, "getDate\0getDay\0getFullYear\0getHours\0getMilliseconds\0getMinutes\0getMonth\0getSeconds\0getTime\0getTime\0getTimezoneOffset\0setDate\0setFullYear\0setHours\0setMilliseconds\0setMinutes\0setMonth\0setSeconds\0toISOString\0toString\0toUTCString\0valueOf\0");
FLASH_STR(jswSymbols_Error_proto_str, "toString\0");
FLASH_STR(jswSymbols_SyntaxError_proto_str, "toString\0");
FLASH_STR(jswSymbols_TypeError_proto_str, "toString\0");
FLASH_STR(jswSymbols_InternalError_proto_str, "toString\0");
FLASH_STR(jswSymbols_ReferenceError_proto_str, "toString\0");
FLASH_STR(jswSymbols_E_str, "FFT\0HSBtoRGB\0clip\0convolve\0dumpLockedVars\0dumpStr\0dumpTimers\0enableWatchdog\0getAddressOf\0getAnalogVRef\0getErrorFlags\0getFlags\0getSizeOf\0getTemperature\0hwRand\0interpolate\0interpolate2d\0kickWatchdog\0lockConsole\0mapInPlace\0memoryArea\0nativeCall\0reverseByte\0setBootCode\0setClock\0setFlags\0setPassword\0setTimeZone\0srand\0sum\0toArrayBuffer\0toString\0toUint8Array\0variance\0");
FLASH_STR(jswSymbols_Flash_str, "\0");
FLASH_STR(jswSymbols_console_str, "log\0");
FLASH_STR(jswSymbols_JSON_str, "parse\0stringify\0");
FLASH_STR(jswSymbols_Modules_str, "addCached\0getCached\0removeAllCached\0removeCached\0");
FLASH_STR(jswSymbols_Pin_proto_str, "getInfo\0getMode\0mode\0read\0reset\0set\0toggle\0write\0writeAtTime\0");
FLASH_STR(jswSymbols_Number_str, "MAX_VALUE\0MIN_VALUE\0NEGATIVE_INFINITY\0NaN\0POSITIVE_INFINITY\0");
FLASH_STR(jswSymbols_Number_proto_str, "toFixed\0");
FLASH_STR(jswSymbols_Object_proto_str, "clone\0emit\0hasOwnProperty\0length\0on\0removeAllListeners\0removeListener\0toString\0valueOf\0");
FLASH_STR(jswSymbols_Object_str, "assign\0create\0defineProperties\0defineProperty\0getOwnPropertyDescriptor\0getOwnPropertyNames\0getPrototypeOf\0keys\0setPrototypeOf\0");
FLASH_STR(jswSymbols_Function_proto_str, "apply\0bind\0call\0replaceWith\0");
FLASH_STR(jswSymbols_process_str, "env\0memory\0version\0");
FLASH_STR(jswSymbols_Promise_str, "all\0reject\0resolve\0");
FLASH_STR(jswSymbols_Promise_proto_str, "catch\0then\0");
FLASH_STR(jswSymbols_Port_proto_str, "set\0");
FLASH_STR(jswSymbols_RegExp_proto_str, "exec\0test\0");
FLASH_STR(jswSymbols_String_proto_str, "charAt\0charCodeAt\0indexOf\0lastIndexOf\0length\0replace\0slice\0split\0substr\0substring\0toLowerCase\0toUpperCase\0trim\0");
FLASH_STR(jswSymbols_String_str, "fromCharCode\0");
FLASH_STR(jswSymbols_Math_str, "E\0LN10\0LN2\0LOG10E\0LOG2E\0PI\0SQRT1_2\0SQRT2\0abs\0acos\0asin\0atan\0atan2\0ceil\0clip\0cos\0exp\0floor\0log\0max\0min\0pow\0random\0round\0sin\0sqrt\0tan\0wrap\0");

const JswSymList jswSymbolTables[] FLASH_SECT = {
  {jswSymbols_global, jswSymbols_global_str, 123},
  {jswSymbols_Array_proto, jswSymbols_Array_proto_str, 20},
  {jswSymbols_Array, jswSymbols_Array_str, 1},
  {jswSymbols_ArrayBufferView_proto, jswSymbols_ArrayBufferView_proto_str, 13},
  {jswSymbols_DataView_proto, jswSymbols_DataView_proto_str, 16},
  {jswSymbols_Date, jswSymbols_Date_str, 2},
  {jswSymbols_Date_proto, jswSymbols_Date_proto_str, 22},
  {jswSymbols_Error_proto, jswSymbols_Error_proto_str, 1},
  {jswSymbols_SyntaxError_proto, jswSymbols_SyntaxError_proto_str, 1},
  {jswSymbols_TypeError_proto, jswSymbols_TypeError_proto_str, 1},
  {jswSymbols_InternalError_proto, jswSymbols_InternalError_proto_str, 1},
  {jswSymbols_ReferenceError_proto, jswSymbols_ReferenceError_proto_str, 1},
  {jswSymbols_JSON, jswSymbols_JSON_str, 2},
  {jswSymbols_Modules, jswSymbols_Modules_str, 4},
  {jswSymbols_Number, jswSymbols_Number_str, 5},
  {jswSymbols_Number_proto, jswSymbols_Number_proto_str, 1},
  {jswSymbols_Object_proto, jswSymbols_Object_proto_str, 9},
  {jswSymbols_Object, jswSymbols_Object_str, 9},
  {jswSymbols_Function_proto, jswSymbols_Function_proto_str, 4},
  {jswSymbols_process, jswSymbols_process_str, 3},
  {jswSymbols_Promise, jswSymbols_Promise_str, 3},
  {jswSymbols_Promise_proto, jswSymbols_Promise_proto_str, 2},
  {jswSymbols_Port_proto, jswSymbols_Port_proto_str, 1},
  {jswSymbols_RegExp_proto, jswSymbols_RegExp_proto_str, 2},
  {jswSymbols_String, jswSymbols_String_str, 1},
  {jswSymbols_Math, jswSymbols_Math_str, 28},
};


const JswSymList *jswGetSymbolListForConstructorProto(JsVar *constructor) {
  void *constructorPtr = constructor->varData.native.ptr;
  if (constructorPtr==(void*)jswrap_dataview_constructor) return &jswSymbolTables[jswSymbolIndex_DataView_proto];
  if (constructorPtr==(void*)jswrap_date_constructor) return &jswSymbolTables[jswSymbolIndex_Date_proto];
  if (constructorPtr==(void*)jswrap_error_constructor) return &jswSymbolTables[jswSymbolIndex_Error_proto];
  if (constructorPtr==(void*)jswrap_syntaxerror_constructor) return &jswSymbolTables[jswSymbolIndex_SyntaxError_proto];
  if (constructorPtr==(void*)jswrap_typeerror_constructor) return &jswSymbolTables[jswSymbolIndex_TypeError_proto];
  if (constructorPtr==(void*)jswrap_internalerror_constructor) return &jswSymbolTables[jswSymbolIndex_InternalError_proto];
  if (constructorPtr==(void*)jswrap_referenceerror_constructor) return &jswSymbolTables[jswSymbolIndex_ReferenceError_proto];
  if (constructorPtr==(void*)jswrap_promise_constructor) return &jswSymbolTables[jswSymbolIndex_Promise_proto];
  if (constructorPtr==(void*)jswrap_regexp_constructor) return &jswSymbolTables[jswSymbolIndex_RegExp_proto];
  if (constructorPtr==(void*)jswrap_port_constructor) return &jswSymbolTables[jswSymbolIndex_Port_proto];
  return 0;
}


JsVar *jswFindBuiltInFunction(JsVar *parent, const char *name) {
  JsVar *v;
  if (parent && !jsvIsRoot(parent)) {
    // ------------------------------------------ INSTANCE + STATIC METHODS
    if (jsvIsNativeFunction(parent)) {
      JswSymList *l = jswGetSymbolListForObject(parent);
      if (l) {
        v = jswBinarySearch(l, parent, name);
        if (v) return v;
      }
    }
    if (jsvIsArray(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Array_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsArrayBuffer(parent) && parent->varData.arraybuffer.type!=ARRAYBUFFERVIEW_ARRAYBUFFER) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsNumeric(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Number_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsFunction(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Function_proto], parent, name);
      if (v) return v;
    }
    if (jsvIsString(parent)) {
      v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_String_proto], parent, name);
      if (v) return v;
    }
    // ------------------------------------------ INSTANCE METHODS WE MUST CHECK CONSTRUCTOR FOR
    JsVar *proto = jsvIsObject(parent)?jsvSkipNameAndUnLock(jsvFindChildFromString(parent, JSPARSE_INHERITS_VAR, false)):0;
    JsVar *constructor = jsvIsObject(proto)?jsvSkipNameAndUnLock(jsvFindChildFromString(proto, JSPARSE_CONSTRUCTOR_VAR, false)):0;
    jsvUnLock(proto);
    if (constructor && jsvIsNativeFunction(constructor)) {
      const JswSymList *l = jswGetSymbolListForConstructorProto(constructor);
      jsvUnLock(constructor);
      if (l) {
        v = jswBinarySearch(l, parent, name);
        if (v) return v;
      }
    } else {
      jsvUnLock(constructor);
    }
    // ------------------------------------------ METHODS ON OBJECT
    v = jswBinarySearch(&jswSymbolTables[jswSymbolIndex_Object_proto], parent, name);
    if (v) return v;
  } else { /* if (!parent) */
    // ------------------------------------------ FUNCTIONS
    // Handle pin names - eg LED1 or D5 (this is hardcoded in build_jsfunctions.py)
//    Pin pin = jshGetPinFromString(name);
//    if (pin != PIN_UNDEFINED) {
//      return jsvNewFromPin(pin);
//    }
    return jswBinarySearch(&jswSymbolTables[jswSymbolIndex_global], parent, name);
  }
  return 0;
}


const JswSymList *jswGetSymbolListForObject(JsVar *parent) {
  if (jsvIsNativeFunction(parent)) {
    if ((void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) return &jswSymbolTables[jswSymbolIndex_Array];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_date_constructor) return &jswSymbolTables[jswSymbolIndex_Date];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_JSON_JSON) return &jswSymbolTables[jswSymbolIndex_JSON];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Modules_Modules) return &jswSymbolTables[jswSymbolIndex_Modules];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) return &jswSymbolTables[jswSymbolIndex_Number];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_object_constructor) return &jswSymbolTables[jswSymbolIndex_Object];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_process_process) return &jswSymbolTables[jswSymbolIndex_process];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_promise_constructor) return &jswSymbolTables[jswSymbolIndex_Promise];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) return &jswSymbolTables[jswSymbolIndex_String];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_Math_Math) return &jswSymbolTables[jswSymbolIndex_Math];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_port_constructor) return &jswSymbolTables[jswSymbolIndex_Port];
  }
  if (parent==execInfo.root) return &jswSymbolTables[jswSymbolIndex_global];
  return 0;
}


const JswSymList *jswGetSymbolListForObjectProto(JsVar *parent) {
  if (jsvIsNativeFunction(parent)) {
    if ((void*)parent->varData.native.ptr==(void*)jswrap_array_constructor) return &jswSymbolTables[jswSymbolIndex_Array_proto];
    if ((void*)parent->varData.native.ptr==(void*)gen_jswrap_ArrayBufferView_ArrayBufferView) return &jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_number_constructor) return &jswSymbolTables[jswSymbolIndex_Number_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_function_constructor) return &jswSymbolTables[jswSymbolIndex_Function_proto];
    if ((void*)parent->varData.native.ptr==(void*)jswrap_string_constructor) return &jswSymbolTables[jswSymbolIndex_String_proto];
  }
  JsVar *constructor = jsvIsObject(parent)?jsvSkipNameAndUnLock(jsvFindChildFromString(parent, JSPARSE_CONSTRUCTOR_VAR, false)):0;
  if (constructor && jsvIsNativeFunction(constructor)) {
    const JswSymList *l = jswGetSymbolListForConstructorProto(constructor);
    jsvUnLock(constructor);
    if (l) return l;
  }
  if (jsvIsArray(parent)) return &jswSymbolTables[jswSymbolIndex_Array_proto];
  if (jsvIsArrayBuffer(parent) && parent->varData.arraybuffer.type!=ARRAYBUFFERVIEW_ARRAYBUFFER) return &jswSymbolTables[jswSymbolIndex_ArrayBufferView_proto];
  if (jsvIsNumeric(parent)) return &jswSymbolTables[jswSymbolIndex_Number_proto];
  if (jsvIsFunction(parent)) return &jswSymbolTables[jswSymbolIndex_Function_proto];
  if (jsvIsString(parent)) return &jswSymbolTables[jswSymbolIndex_String_proto];
  return &jswSymbolTables[jswSymbolIndex_Object_proto];
}


bool jswIsBuiltInObject(const char *name) {
  return
strcmp(name, "Array")==0 ||
    strcmp(name, "ArrayBuffer")==0 ||
    strcmp(name, "ArrayBufferView")==0 ||
    strcmp(name, "Uint8Array")==0 ||
    strcmp(name, "Uint8ClampedArray")==0 ||
    strcmp(name, "Int8Array")==0 ||
    strcmp(name, "Uint16Array")==0 ||
    strcmp(name, "Int16Array")==0 ||
    strcmp(name, "Uint32Array")==0 ||
    strcmp(name, "Int32Array")==0 ||
    strcmp(name, "Float32Array")==0 ||
    strcmp(name, "Float64Array")==0 ||
    strcmp(name, "DataView")==0 ||
    strcmp(name, "Date")==0 ||
    strcmp(name, "Error")==0 ||
    strcmp(name, "SyntaxError")==0 ||
    strcmp(name, "TypeError")==0 ||
    strcmp(name, "InternalError")==0 ||
    strcmp(name, "ReferenceError")==0 ||
    strcmp(name, "Function")==0 ||
    strcmp(name, "console")==0 ||
    strcmp(name, "JSON")==0 ||
    strcmp(name, "Modules")==0 ||
    strcmp(name, "Port")==0 ||
    strcmp(name, "Number")==0 ||
    strcmp(name, "Object")==0 ||
    strcmp(name, "Boolean")==0 ||
    strcmp(name, "process")==0 ||
    strcmp(name, "Promise")==0 ||
    strcmp(name, "RegExp")==0 ||
    strcmp(name, "String")==0 ||
    strcmp(name, "Waveform")==0 ||
    strcmp(name, "Math")==0 ||
    strcmp(name, "Graphics")==0 ||
    strcmp(name, "url")==0 ||
    strcmp(name, "Server")==0 ||
    strcmp(name, "Socket")==0 ||
    strcmp(name, "dgramSocket")==0 ||
    strcmp(name, "httpSrv")==0 ||
    strcmp(name, "httpSRq")==0 ||
    strcmp(name, "httpSRs")==0 ||
    strcmp(name, "httpCRq")==0 ||
    strcmp(name, "httpCRs")==0 ||
    strcmp(name, "NRF")==0 ||
    strcmp(name, "BluetoothDevice")==0 ||
    strcmp(name, "BluetoothRemoteGATTCharacteristic")==0 ||
    strcmp(name, "BluetoothRemoteGATTServer")==0 ||
    strcmp(name, "BluetoothRemoteGATTService")==0;
}


void *jswGetBuiltInLibrary(const char *name) {
if (strcmp(name, "Flash")==0) return (void*)gen_jswrap_Flash_Flash;
if (strcmp(name, "net")==0) return (void*)gen_jswrap_net_net;
if (strcmp(name, "dgram")==0) return (void*)gen_jswrap_dgram_dgram;
if (strcmp(name, "http")==0) return (void*)gen_jswrap_http_http;
if (strcmp(name, "NetworkJS")==0) return (void*)gen_jswrap_NetworkJS_NetworkJS;
if (strcmp(name, "neopixel")==0) return (void*)gen_jswrap_neopixel_neopixel;
  return 0;
}


/** Given a variable, return the basic object name of it */
const char *jswGetBasicObjectName(JsVar *var) {
  if (jsvIsFunction(var)) return "Function";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT32) return "Int32Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==(ARRAYBUFFERVIEW_UINT8|ARRAYBUFFERVIEW_CLAMPED)) return "Uint8ClampedArray";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT32) return "Uint32Array";
  if (jsvIsPin(var)) return "Pin";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_ARRAYBUFFER) return "ArrayBuffer";
  if (jsvIsObject(var)) return "Object";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT8) return "Uint8Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_UINT16) return "Uint16Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_FLOAT64) return "Float64Array";
  if (jsvIsNumeric(var)) return "Number";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT8) return "Int8Array";
  if (jsvIsArray(var)) return "Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_INT16) return "Int16Array";
  if (jsvIsArrayBuffer(var) && var->varData.arraybuffer.type==ARRAYBUFFERVIEW_FLOAT32) return "Float32Array";
  if (jsvIsString(var)) return "String";
  return 0;
}


/** Given the name of a Basic Object, eg, Uint8Array, String, etc. Return the prototype object's name - or 0. */
const char *jswGetBasicObjectPrototypeName(const char *objectName) {
  if (!strcmp(objectName, "Uint8Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint8ClampedArray")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int8Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint16Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int16Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Uint32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Int32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Float32Array")) return "ArrayBufferView";
  if (!strcmp(objectName, "Float64Array")) return "ArrayBufferView";
  return strcmp(objectName,"Object") ? "Object" : 0;
}


/** Tasks to run on Idle. Returns true if either one of the tasks returned true (eg. they're doing something and want to avoid sleeping) */
bool jswIdle() {
//  bool wasBusy = false;
//  if (jswrap_pipe_idle()) wasBusy = true;
//  if (jswrap_waveform_idle()) wasBusy = true;
//  return wasBusy;
	return true;
}


/** Tasks to run on Initialisation */
void jswInit() {
}


/** Tasks to run on Deinitialisation */
void jswKill() {
}


